server:
  port: ${PORT:9090}

spring:
  application:
    name: kafka-client
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: my-topic
    consumer:
      group-id: my-group
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
